# Futher Reading

If you're looking for a place to learn more about R, then I'd recommend the [GardenersOwn.co.uk](http://www.gardenersown.co.uk/Education/Lectures/R/){target="_blank"} website, which has some tutorials on basic statistics in R. There's an almost infinite amount of questions and answers on various R topics on [StackOverflow.com](https://stackoverflow.com/questions/tagged/r){target="_blank"}. In addition I'd also really recommend the following accounts on Twitter: [R4DataScience](https://twitter.com/r4dscommunity){target="_blank"}, which is an account with the explicit purpose to make R more accessible. Related to this is also [Thomas Mock](https://twitter.com/thomas_mock){target="_blank"}, who organizes a weekly exercise, called _TidyTuesday_, which is a initiative where they share a public dataset, and invite all interested Twitter users to share their statistics and particularly their data visualizations. I'd also recommend following [Hadley Wickham](https://twitter.com/hadleywickham){target="_blank"} and [Thomas Lin Pedersen](https://twitter.com/thomasp85){target="_blank"}. Both work for Rstudio, Hadley Wickham is the Chief Scientist and brain behind the `{ggplot2}` package. Both Hadley and Thomas work on the `{tidyverse}` package. Thomas is also interesting to follow for his genetive artwork, which he creates in part by using R. I'd also recommend checking the Twitter profile from our very own [Dan Quintana](https://twitter.com/dsquintana){target="_blank"}, he posts little videos occasionally where he live codes to solve a certain problem. In that same category, I'd also recommend searching [YouTube](https://youtube.com){target="_blank"} for tutorials. In particular live coding videos are useful since you can follow along in their thought and coding process.